create table if not exists gallery (
  id bigint generated by default as identity primary key,
  caption text default '',
  image_url text not null,
  created_at timestamptz default now()
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  description text default '',
  image_url text not null,
  created_at timestamptz default now()
);

create table if not exists contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text,
  service text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'replied', 'archived')),
  created_at timestamptz default now()
);

create table if not exists about_content (
  id bigint generated by default as identity primary key,
  hero_title text default '',
  hero_subtitle text default '',
  hero_description text default '',
  mission text default '',
  vision text default '',
  updated_at timestamptz default now()
);

create table if not exists site_settings (
  id bigint generated by default as identity primary key,
  site_name text default '',
  site_email text default '',
  site_phone text default '',
  site_address text default '',
  site_description text default '',
  social_links jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists admin_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  role text not null default 'admin' check (role in ('admin', 'editor', 'moderator')),
  full_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (auth_user_id)
);

create index if not exists idx_contact_status on contact_submissions(status);
